/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.main;

import gui.manage.ToolManagerDisplay;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author Meng
 */
public class MainDisplay extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainDisplay() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        this.setSize(400, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel infoPanel = new JPanel();
        JLabel appLabel = new JLabel();
        JPanel applicationPanel = new JPanel();
        JButton toolManagerBtn = new JButton();
        JButton workbenchBtn = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock Market Prediction Framework");
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setName(""); // NOI18N
        setResizable(false);

        infoPanel.setLayout(new BorderLayout());

        appLabel.setText("Stock Market Prediction Framework");
        appLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        infoPanel.add(appLabel, BorderLayout.CENTER);

        getContentPane().add(infoPanel, BorderLayout.CENTER);

        applicationPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Applications"));
        applicationPanel.setLayout(new GridLayout(4, 0));

        toolManagerBtn.setText("Tools Manager");
        toolManagerBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                toolManagerBtnActionPerformed(evt);
            }
        });
        applicationPanel.add(toolManagerBtn);

        workbenchBtn.setText("Workbench");
        workbenchBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                workbenchBtnActionPerformed(evt);
            }
        });
        applicationPanel.add(workbenchBtn);

        getContentPane().add(applicationPanel, BorderLayout.EAST);
        applicationPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toolManagerBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_toolManagerBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToolManagerDisplay().setVisible(true);
            }
        });
    }//GEN-LAST:event_toolManagerBtnActionPerformed

    private void workbenchBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_workbenchBtnActionPerformed
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new gui.manage.ToolManagerDisplay().setVisible(true);
//            }
//        });
    }//GEN-LAST:event_workbenchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDisplay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
